---
title: "Graphing Using ggplot Part-3"
output: html_notebook
---

```{r}
library(ggplot2)
```

```{r}
# Load the mpg dataset
data('mpg')
mpgData = mpg

# Print the first five rows (or samples) in the data frame
head(mpgData, 5)
```

```{r}
# Plot a scatter plot of mileage w.r.t. displacement
ggplot(data = mpgData) + 
  geom_?(mapping = aes(x = ?, y = ?))
```

```{r}
# Plot a bar chart w.r.t. number of cylinders
ggplot(data = mpgData) +
  geom_?(mapping = aes(? = ?))
```

```{r}
#  Which stat geom_bar uses by default?

```

```{r}
# Using a stat explicitly
ggplot(data = mpgData) +
  ?(mapping = aes(x = cyl))
```

```{r}
tempData = data.frame(table(mpgData$cyl))
colnames(tempData) = c('cyl', 'frequency')
```

```{r}
# Plot a bar chart w.r.t. number of cylinders directly
ggplot(data = tempData) +
  geom_bar(mapping = aes(x = cyl, y = frequency))
```

```{r}
#  Plot a bar chart of proportion, rather than count w.r.t. number of cylinders
ggplot(data = mpgData) +
  geom_bar(mapping = aes(x = cyl))
```

```{r}
# Plot a histogram of engine displacement
ggplot(data = mpgData) +
  geom_histogram(aes(x = displ, y = ..count..), binwidth = 0.5, color = 'black', fill = 'steelblue', alpha = 0.4) +
  labs(x = 'Displacement (litres)', y = 'Frequency')
```

```{r}
# Plot a bar chart w.r.t. number of cylinders and class using color and fill
ggplot(data = mpgData) +
  geom_bar(mapping = aes(x = cyl, fill = ?))
```


